# openapi: 3.0.0
# info:
#   version: "1.0.0"
#   title: "API_Example"
#   description: "Swagger 실습을 위한 API_Example "
# # Added by API Auto Mocking Plugin
# servers:
#   - description: SwaggerHub API Auto Mocking
#     url: https://virtserver.swaggerhub.com/hyeong412/API_Example/1.0.0
#   - description: JSON Placeholder API
#     url: https://jsonplaceholder.typicode.com/
#   - description: GOOGLE API
#     url: https://www.google.com/
# paths:
#   /todos/{id}:
#     get:
#       summary: Return a user by ID
#       parameters:
#         - name: id
#           in: path
#           required: true
#           description: The ID of the user to return
#           schema:
#             type: integer
#       responses:
#         "200":
#           description: OK
#           content:
#             application/json:
#               schema:
#                 type: object
#                 properties:
#                   userId:
#                     type: integer
#                   id:
#                     type: integer
#                   title:
#                     type: string
#                   completed:
#                     type: boolean
#   /complete/search:
#     get:
#       summary: 자동완성 검색결과 반환
#       parameters:
#         - name: q
#           in: query
#           schema:
#             type: string
#         - name: client
#           in: query
#           schema:
#             type: string
#       responses:
#         "200":
#           description: A text file
#           content:
#             text/plain:
#               schema:
#                 type: string
